// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RezeptbuchAPI.Models;

#nullable disable

namespace RezeptbuchAPI.Migrations
{
    [DbContext(typeof(RecipeBookContext))]
    [Migration("20250601024121_Ref")]
    partial class Ref
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recipe", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageHash")
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Hash");

                    b.HasIndex("ImageHash");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RezeptbuchAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipeHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeHash");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RezeptbuchAPI.Models.Image", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Hash");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RezeptbuchAPI.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("InstructionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstructionId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RezeptbuchAPI.Models.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RecipeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeHash");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("Recipe", b =>
                {
                    b.HasOne("RezeptbuchAPI.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageHash");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RezeptbuchAPI.Models.Category", b =>
                {
                    b.HasOne("Recipe", null)
                        .WithMany("Categories")
                        .HasForeignKey("RecipeHash");
                });

            modelBuilder.Entity("RezeptbuchAPI.Models.Ingredient", b =>
                {
                    b.HasOne("RezeptbuchAPI.Models.Instruction", "Instruction")
                        .WithMany("Ingredients")
                        .HasForeignKey("InstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruction");
                });

            modelBuilder.Entity("RezeptbuchAPI.Models.Instruction", b =>
                {
                    b.HasOne("Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Recipe", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("RezeptbuchAPI.Models.Instruction", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
